.PHONY: all , clean

all:
	gcc -o run-exam1 example-1thread.c -pthread
	gcc -o run-exam2 example-2thread.c -pthread

clean:
	rm -rf run-exam1
	rm -rf run-exam2
	rm -rf dulieu1.txt dulieu2.txt